from html_top8_video import make_top8_video
from top16_html import rodape_html

# {3: [['DMX | RonaldinhoBR 3 - JUNINHO-RAS 2', 3, 'RonaldinhoBR', 2, 'JUNINHO-RAS']], 2: [['DMX | RonaldinhoBR 3 - JUNINHO-RAS 2', 3, 'RonaldinhoBR', 2, 'JUNINHO-RAS']], -6: [['JUNINHO-RAS 3 - GO | DARK 1', 3, 'JUNINHO-RAS', 1, 'DARK']], -5: [['GO | DARK 3 - NamikazeExTM 2', 3, 'DARK', 2, 'NamikazeExTM']], 1: [['NamikazeExTM 0 - DMX | RonaldinhoBR 3', 0, 'NamikazeExTM', 3, 'RonaldinhoBR'], ['JUNINHO-RAS 3 - archlion 1', 3, 'JUNINHO-RAS', 1, 'archlion']], -4: [['archlion 0 - GO | DARK 3', 0, 'archlion', 3, 'DARK'], ['NamikazeExTM 3 - SFT_CAPAO 0', 3, 'NamikazeExTM', 0, 'SFT_CAPAO']], -3: [['Shodown | Jah_lexe 1 - GO | DARK 3', 1, 'Jah_lexe', 3, 'DARK'], ['DQ', 'DQ', 'vitinho', 0, 'SFT_CAPAO']]}

lugares = {-3: [["", 0, "Juca", 0, "Petra"]], -4: [["", 0, "Jaaaaaaaaaaaaaaauca", 0, "Petra"]], 1: [["", 0, "Juca", 0, "Petra"]]}
lugares = {'data': {'event': {'sets': {'nodes': [{'round': -3, 'displayScore': None, 'slots': [{'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'Zangief_bolado'}]}}, {'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'HorusPaulin'}]}}]}, {'round': -4, 'displayScore': None, 'slots': [{'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'NotPedro'}]}}, {'standing': None, 'entrant': None}]}, {'round': -4, 'displayScore': None, 'slots': [{'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'Saitama9274'}]}}, {'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'Mimam'}]}}]}, {'round': -5, 'displayScore': None, 'slots': [{'standing': None, 'entrant': None}, {'standing': None, 'entrant': None}]}, {'round': -6, 'displayScore': None, 'slots': [{'standing': None, 'entrant': None}, {'standing': None, 'entrant': None}]}, {'round': 2, 'displayScore': None, 'slots': [{'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'DARK'}]}}, {'standing': {'stats': {'score': {'value': None}}}, 'entrant': {'participants': [{'gamerTag': 'Maroto06'}]}}]}, {'round': 3, 'displayScore': None, 'slots': [{'standing': None, 'entrant': None}, {'standing': None, 'entrant': None}]}, {'round': 3, 'displayScore': None, 'slots': [{'standing': None, 'entrant': None}, {'standing': None, 'entrant': None}]}, {'round': 1, 'displayScore': 'TRUE | DARK 3 - Saitama9274 0', 'slots': [{'standing': {'stats': {'score': {'value': 3}}}, 'entrant': {'participants': [{'gamerTag': 'DARK'}]}}, {'standing': {'stats': {'score': {'value': 0}}}, 'entrant': {'participants': [{'gamerTag': 'Saitama9274'}]}}]}, {'round': 1, 'displayScore': 'GuaruFighters | NotPedro 2 - Maroto06 3', 'slots': [{'standing': {'stats': {'score': {'value': 2}}}, 'entrant': {'participants': [{'gamerTag': 'NotPedro'}]}}, {'standing': {'stats': {'score': {'value': 3}}}, 'entrant': {'participants': [{'gamerTag': 'Maroto06'}]}}]}, {'round': -3, 'displayScore': 'Neguinho 2 - Mamute | Mimam 3', 'slots': [{'standing': {'stats': {'score': {'value': 2}}}, 'entrant': {'participants': [{'gamerTag': 'Neguinho'}]}}, {'standing': {'stats': {'score': {'value': 3}}}, 'entrant': {'participants': [{'gamerTag': 'Mimam'}]}}]}]}}}, 'extensions': {'cacheControl': {'version': 1, 'hints': [{'path': ['event'], 'maxAge': 60, 'scope': 'PRIVATE'}]}, 'queryComplexity': 0}, 'actionRecords': []}
lugares = {-3: [["", 0, "Juca", 0, "Petra"]], -4: [["", 0, "Jaaaaaaaaaaaaaaauca", 0, "Petra"]], 1: [["", 0, "Juca", 0, "Petra"]]}
if __name__ == '__main__':
    print(make_top8_video(lugares, True))
    print(rodape_html(lugares, True))
